name: 'Checkout QMK firmware'

inputs:
    version:
        type: string
        required: true
    path:
        default: '__qmk_vial__'
        type: string
        required: false

runs:
    using: 'composite'
    steps:
    - name: Checkout vial-qmk
        uses: actions/checkout@v4
        with:
            path: ${{ inputs.path }}
            repository: sekigon-gonnoc/vial-qmk
            submodules: recursive
            ref: ${{ inputs.version }}

    - name: Setup QMK
        shell: bash
        run: qmk setup --home ${{ inputs.path }} --yes
